---
- name: Remove broken or old Nodejs/NPM
  apt:
    name: ['nodejs', 'npm', 'node-shared']
    state: absent
    purge: yes
  become: true

- name: Install NodeSource setup requirements
  apt:
    name: ['curl', 'ca-certificates', 'gnupg']
    state: present
  become: true

- name: Add NodeSource GPG key and repository (Node 20)
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  become: true

- name: Install Nodejs (includes NPM) and Nginx
  apt:
    name:
      - nodejs
      - nginx
      - mysql-client
    state: present
    update_cache: yes
  become: true

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
  become: true

- name: Clone Book Review Repository
  git:
    repo: "https://github.com/pravinmishraaws/book-review-app.git"
    dest: "/home/{{ admin_username }}/app"
    version: main
    force: yes
  become: true
  become_user: "{{ admin_username }}"

- name: Create Database if not exists
  shell: |
    mysql -h {{ db_host }} -u {{ mysql_admin_username }} -p'{{ mysql_admin_password }}' --ssl-mode=REQUIRED \
    -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"
  become: true
  become_user: "{{ admin_username }}"
  register: db_create
  changed_when: "'1 row affected' in db_create.stdout"

# --- BACKEND SETUP ---
- name: Install Backend dependencies
  npm:
    path: "/home/{{ admin_username }}/app/backend"
  become: true
  become_user: "{{ admin_username }}"

- name: Configure Backend .env
  template:
    src: backend_env.j2
    dest: "/home/{{ admin_username }}/app/backend/.env"
  become: true
  become_user: "{{ admin_username }}"

- name: Start Backend with PM2
  shell: |
    pm2 delete backend || true
    pm2 start src/server.js --name "backend"
  args:
    chdir: "/home/{{ admin_username }}/app/backend"
  become: true
  become_user: "{{ admin_username }}"

# --- FRONTEND SETUP ---
- name: Install Frontend dependencies
  npm:
    path: "/home/{{ admin_username }}/app/frontend"
  become: true
  become_user: "{{ admin_username }}"

- name: Configure Frontend .env
  copy:
    dest: "/home/{{ admin_username }}/app/frontend/.env"
    content: "NEXT_PUBLIC_API_URL=/api"
  become: true
  become_user: "{{ admin_username }}"

- name: Build Frontend with Environment Variable
  shell: |
    export PATH=$PATH:$(pwd)/node_modules/.bin
    export NEXT_PUBLIC_API_URL=/api
    npm run build
  args:
    chdir: "/home/{{ admin_username }}/app/frontend"
    executable: /bin/bash
  become: true
  become_user: "{{ admin_username }}"

- name: Restart Frontend Process
  shell: |
    pm2 delete frontend || true
    pm2 start npm --name "frontend" -- start
  args:
    chdir: "/home/{{ admin_username }}/app/frontend"
  become: true
  become_user: "{{ admin_username }}"

- name: Start Frontend with PM2
  shell: |
    pm2 delete frontend || true
    pm2 start npm --name "frontend" -- start
  args:
    chdir: "/home/{{ admin_username }}/app/frontend"
  become: true
  become_user: "{{ admin_username }}"