---
- name: Clone Book Review Repository
  git:
    repo: "{{ app_repo }}"
    dest: "/home/{{ admin_username }}/app"
    version: main
    force: yes
  become: true
  become_user: "{{ admin_username }}"

- name: Install Backend dependencies
  npm:
    path: "/home/{{ admin_username }}/app/backend"
  become: true
  become_user: "{{ admin_username }}"

- name: Deploy .env configuration
  template:
    src: backend_env.j2
    dest: "/home/{{ admin_username }}/app/backend/.env"
    mode: '0600'
  become: true
  become_user: "{{ admin_username }}"
  notify: Restart backend

- name: Start Application with PM2
  shell: |
    pm2 describe book-backend > /dev/null || pm2 start src/server.js --name "book-backend"
  args:
    chdir: "/home/{{ admin_username }}/app/backend"
  become: true
  become_user: "{{ admin_username }}"
  register: pm2_result
  changed_when: "'starting' in pm2_result.stdout"