---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx site
  template:
    src: nginx_proxy.j2
    dest: /etc/nginx/sites-available/bookreview
  notify: Reload nginx

- name: Enable site and remove default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create symlink for site
  file:
    src: /etc/nginx/sites-available/bookreview
    dest: /etc/nginx/sites-enabled/bookreview
    state: link